import Head from 'next/head'
import Image from 'next/image'
import Navbar from '@/components/Navbar'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Login from '@/components/Login'
import markets from './markets'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <p className={styles.description}>Welcome to Markets App, Login / Signup below to view current market prices</p>

        <Login />

        <Link className={styles.code} href="../markets">
          View Markets
        </Link>


      </main>
    </>
  )
}
